spring.application.name=order-service

server.port=8082

#user.service.base-url=http://localhost:8081

user.service.base-url=http://USER-SERVICE

payment.service.base-url=http://PAYMENT-SERVICE
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Resilience4j Retry
resilience4j.retry.instances.paymentService.max-attempts=3
resilience4j.retry.instances.paymentService.wait-duration=500ms

eureka.instance.prefer-ip-address=true


